import 'package:flutter/foundation.dart';

class Post {
  final int userId;
  final int id;
  final String title;
  final String body;

  Post(
      {required this.userId,
      required this.id,
      required this.title,
      required this.body});

//هنا يجب أن نلتزم كما مكتوب بال back
  factory Post.fromJson(Map<String, dynamic> jsonData) {
    return Post(
        userId: jsonData['userId'],
        id: jsonData['id'],
        title: jsonData['title'],
        body: jsonData['body'],
    );
  }
}


class Posts{

  final List<dynamic> postlist;

Posts({required this.postlist});

  factory Posts.fromJson(Map<String, dynamic> jsonData) {
    return Posts(
      postlist: jsonData['postlist'],

    );
  }
}













/*
class Autogenerated {
  int? albumId;
  int? id;
  String? title;
  String? url;
  String? thumbnailUrl;

  Autogenerated(
      {this.albumId, this.id, this.title, this.url, this.thumbnailUrl});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    albumId = json['albumId'];
    id = json['id'];
    title = json['title'];
    url = json['url'];
    thumbnailUrl = json['thumbnailUrl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['albumId'] = this.albumId;
    data['id'] = this.id;
    data['title'] = this.title;
    data['url'] = this.url;
    data['thumbnailUrl'] = this.thumbnailUrl;
    return data;
  }
}
*/